### ISSUE TITLE
Will you be upgrading to support version 12 of HotChocolate?

### ISSUE THREAD

**Issue by AcidNoX** [fiakkasa/DataAnnotatedModelValidations#1]
Title.

Currently, I'm getting this error with HC v12:

REQUEST: 
``` gql
mutation ForgottenPassword {
  forgottenPassword(input: {
    email: "test@test.com"
  }) {
    success
    reason
  }
}
```

RESPONSE:
``` json
{
  "errors": [
    {
      "message": "Unexpected Execution Error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "forgottenPassword"
      ],
      "extensions": {
        "message": "Method not found: '!!0 HotChocolate.Resolvers.IResolverContext.ArgumentValue(HotChocolate.NameString)'.",
        "stackTrace": "   at DataAnnotatedModelValidations.ValidatorMiddleware.<>c__DisplayClass3_0.<ReportErrorFactory>b__0(IInputField argument)\r\n   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)\r\n   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()\r\n   at System.Linq.Parallel.SpoolingTaskBase.Work()\r\n   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)\r\n   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location ---\r\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)"
      }
    }
  ],
  "data": {
    "forgottenPassword": null
  }
}```

**Comment by fiakkasa** [comment]
Hi,

Thanks for reaching out. I’m planning to upgrade the package to support HC 12 in October.

BR,

Adam

From: ***@***.***>
Sent: Monday, September 20, 2021 8:48 PM
To: ***@***.***>
Cc: ***@***.***>
Subject: [fiakkasa/DataAnnotatedModelValidations] Will you be upgrading to support version 12 of HotChocolate? (#1)


Title.

Currently, I'm getting this error with HC v12:

REQUEST:

mutation ForgottenPassword {

  forgottenPassword(input: {

    email: ***@***.***"

  }) {

    success

    reason

  }

}

RESPONSE:

{

  "errors": [

    {

      "message": "Unexpected Execution Error",

      "locations": [

        {

          "line": 2,

          "column": 3

        }

      ],

      "path": [

        "forgottenPassword"

      ],

      "extensions": {

        "message": "Method not found: '!!0 HotChocolate.Resolvers.IResolverContext.ArgumentValue(HotChocolate.NameString)'.",

        "stackTrace": "   at DataAnnotatedModelValidations.ValidatorMiddleware.<>c__DisplayClass3_0.<ReportErrorFactory>b__0(IInputField argument)\r\n   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)\r\n   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()\r\n   at System.Linq.Parallel.SpoolingTaskBase.Work()\r\n   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)\r\n   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location ---\r\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)"

      }

    }

  ],

  "data": {

    "forgottenPassword": null

  }

}```

**Comment by AcidNoX** [comment]
Thank so much for the quick reply. 

I’ll keep an eye out for it 👍🏻

Thanks,

Lee
