### ISSUE TITLE
Add support for IIinputFieldDescriptor extension methods?

### ISSUE THREAD

**Issue by onionhammer** [fiakkasa/DataAnnotatedModelValidations#10]
Allowing model validations to be done with code-first (not just annotation-based) inputs.

Say you have an underlying model and you're specifying an IInputObject for it

```C#
descriptor.Field(p => p.Id).RegularExpression("\w+")
```

**Comment by fiakkasa** [comment]
Hi,

Thanks for getting in touch.

I think for your intends and purposes this package https://github.com/appany/AppAny.HotChocolate.FluentValidation might be more inline with your request.

BR,

Adam
