### ISSUE TITLE
Why drop net6.0 already?

### ISSUE THREAD

**Issue by leniency** [fiakkasa/DataAnnotatedModelValidations#15]
I'm curious why you opted to block dotnet 6 from future updates already, barely a week after 8 came out? The latest version doesn't really seem to add anything net7+ specific that I see, so would still be fully compatible. Even the upcoming Hot Chocolate 14 still targets net6.0.

**Comment by fiakkasa** [comment]
Hi,

Thanks for reaching out and your feedback.

The main idea was to support 2 concurrent versions.

I will reinstate .NET 6 support with the next release.

BR

Adam

**Comment by fiakkasa** [comment]
Hi,

A new version 5.1.0 was pushed with reinstated .NET 6 support.

BR,

Adam

**Comment by leniency** [comment]
Excellent, thanks!
