### ISSUE TITLE
Error on optional field

### ISSUE THREAD

**Issue by dakim-sage** [fiakkasa/DataAnnotatedModelValidations#2]
Hi, great job, it works perfectly but I have this error when I use the annotation on optional field.

[MaxLength(10)]
public Optional<string> Test { get; init; }

"extensions": {
                "message": "The field of type HotChocolate.Optional`1[System.String] must be a string, array or ICollection type.",
                "stackTrace": "   at System.ComponentModel.DataAnnotations.MaxLengthAttribute.IsValid(Object value)\r\n   at System.ComponentModel.DataAnnotations.ValidationAttribute.IsValid(Object value, ValidationContext validationContext)\r\n   at System.ComponentModel.DataAnnotations.ValidationAttribute.GetValidationResult(Object value, ValidationContext validationContext)\r\n   at System.ComponentModel.DataAnnotations.Validator.TryValidate(Object value, ValidationContext validationContext, ValidationAttribute attribute, ValidationError& validationError)\r\n   at System.ComponentModel.DataAnnotations.Validator.GetValidationErrors(Object value, ValidationContext validationContext, IEnumerable`1 attributes, Boolean breakOnFirstError)\r\n   at System.ComponentModel.DataAnnotations.Validator.GetObjectPropertyValidationErrors(Object instance, ValidationContext validationContext, Boolean validateAllProperties, Boolean breakOnFirstError)\r\n   at System.ComponentModel.DataAnnotations.Validator.GetObjectValidationErrors(Object instance, ValidationContext validationContext, Boolean validateAllProperties, Boolean breakOnFirstError)\r\n   at System.ComponentModel.DataAnnotations.Validator.TryValidateObject(Object instance, ValidationContext validationContext, ICollection`1 validationResults, Boolean validateAllProperties)\r\n   at DataAnnotatedModelValidations.ValidatorMiddleware.ValidateItem(IReadOnlyDictionary`2 context, Object item, IServiceProvider serviceProvider, List`1 validationResults)\r\n   at DataAnnotatedModelValidations.ValidatorMiddleware.<>c__DisplayClass3_0.<ReportErrorFactory>b__0(IInputField argument)\r\n   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)\r\n   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()\r\n   at System.Linq.Parallel.SpoolingTaskBase.Work()\r\n   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)\r\n   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location ---\r\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)"
            }

**Comment by fiakkasa** [comment]
Hi, thanks for your good words!

Will check it out this weekend and get back to you.

**Comment by fiakkasa** [comment]
Said error appears to be caused by an InvalidCastException coming from the Validator framework: as it cannot cast Optional<string> to string.

Suggestively you could use 

[MaxLength(10)]
public string? Test { get; init; }

**Comment by dakim-sage** [comment]
Hi, Thank you for the quick reply
I solved my problem by declaring a new MaxLengthAttribute which manages Optional type

```
public class MaxLengthHcAttribute : MaxLengthAttribute
    {
        public MaxLengthHcAttribute() : base()
        {
        }
        public MaxLengthHcAttribute(int length) : base(length)
        {
        }
        public override bool IsValid(object value)
        {
            if (value is IOptional optionalValue)
                return optionalValue.HasValue ? base.IsValid(optionalValue.Value) : true;
            return base.IsValid(value);
        }
    }
```

```
[MaxLengthHc(10)]
public Optional<string> Test { get; init; }
```

**Comment by fiakkasa** [comment]
Fantastic! Glad you were able to make it work for you!
