### ISSUE TITLE
Validation on root class ok, but child class doesn't work

### ISSUE THREAD

**Issue by kerrpeter** [fiakkasa/DataAnnotatedModelValidations#4]
When I have the likes of this, it works as expected.
`  public class MyClass
    {
        [MaxLength(20)]
        public string FirstName { get; set; }`

But when I have child class, the validation on the child class seems to be ignored

```
   public class ChildCLass
    {
        [MaxLength(20)]
        public string ChildFirstName { get; set; }
    }

    public class MyClass
    {
        [MaxLength(20)]
        public string FirstName { get; set; }

       public ChildCLass Child { get; set; }
    }
```

**Comment by fiakkasa** [comment]
Hi,

Thanks for getting in touch. To mitigate the above you could implement the IValidatableObject interface on the root object to validate the child object, see example below, consider creating an attribute that automates the below process, or look into https://www.nuget.org/packages/Microsoft.AspNetCore.Components.DataAnnotations.Validation and more specifically the ValidateComplexType Attribute.

```
public class ChildCLass
{
      [MaxLength(20)]
      public string ChildFirstName { get; set; }
}

public class MyClass : IValidatableObject 
{
      [MaxLength(20)]
      public string FirstName { get; set; }

      public ChildCLass Child { get; set; }

      public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
      {
          var errors = new List<ValidationResult>();

            if (!Validator.TryValidateObject(Child , new ValidationContext(Child), errors, true))
            {
                foreach (var error in errors)
                    yield return error;

                errors.Clear();
            }
      }
}
```

Hope this helps!

**Comment by kerrpeter** [comment]
Thanks for that, but while that approach works, it means defining an explicit Validate function for every child class. The great benefit of this package is making Hotchocolate classes behave like ASP.Net controllers with just the annotations. But if I have to explicitly  define the object hierarchy with Validate functions, its not just as convenient. 
How does Aps.Net hanlde this? Does it use reflection?

**Comment by fiakkasa** [comment]
The MVC framework uses a ValidationVisitor to achieve the desired behavior. https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-6.0

Looking at the documentation @ https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.validator.tryvalidateobject?view=net-6.0 and more specifically the **Remarks** section, one can conclude that recursive validation is not supported automatically out of the box.

> This method evaluates each ValidationAttribute instance that is attached to the object type. It also checks whether each property that is marked with RequiredAttribute is provided. It does not recursively validate the property values of the object.

If you need to recursively validate aka go more than 1 level deep you need to instruct the Validator to do so.

Having said that, you can create a custom validation attribute or look into the ValidateComplexType attribute, as per the previous suggestion, to validate complex properties.

```
public class ChildCLass
{
      [MaxLength(20)]
      public string ChildFirstName { get; set; }
}

public class MyClass
{
      [MaxLength(20)]
      public string FirstName { get; set; }
     
      [ValidateChildProperty]
      public ChildCLass Child { get; set; }
}
```

**Comment by kerrpeter** [comment]
I couldn't get the the [ValidateComplexType](https://www.nuget.org/packages/Microsoft.AspNetCore.Components.DataAnnotations.Validation) to work with HotChocolate, and it's a release candidate and not been updated for nearyl 2 years.

But based on you code, I created the customer `ValidateChildProperty` attribute for anyone else needed it, or maybe I'll add a PR for it?
```
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
    public sealed class ValidateChildPropertyAttribute : ValidationAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            var errors = new List<ValidationResult>();

            if (!Validator.TryValidateObject(value, new ValidationContext(value), errors, true))
            {
                return new ValidationResult(FormatErrorMessage(errors[0].ErrorMessage));
            }
            return ValidationResult.Success;
        }
    }
```

**Comment by fiakkasa** [comment]
Good stuff! Please go ahead!
