### ISSUE TITLE
When is the TypeInterceptor used?

### ISSUE THREAD

**Issue by kikaragyozov** [fiakkasa/DataAnnotatedModelValidations#5]
Curious when exactly it's being used, as my code never utilizes it.

**Comment by fiakkasa** [comment]
Hi, the type interceptor is used when the OnBeforeCompleteType is invoked.

In order for your code to utilize this, you will need to ensure your models are annotated and the AddDataAnnotationsValidator method is added after the AddGraphQLServer.

Hope this helps!

**Comment by kikaragyozov** [comment]
That's the thing - in my local environment I've completely removed the type interceptor and everything still works. There is no dictionary in the context data with the name "ValidationAttributes" though, but in my case it was never even used?

**Comment by fiakkasa** [comment]
If memory serves correct, HotChocolate utilizes the type TypeInterceptor to decorate fields with behaviors.
In the DataAnnotatedModelValidations case, either to exclude something from validation or to add any ValidationAttributes.
